# Generated by Django 3.1.7 on 2021-04-09 07:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=30, verbose_name='Наименование')),
                ('itemType', models.CharField(blank=True, choices=[('v', 'Расходный материал'), ('c', 'Инвентарь')], default='c', max_length=1, verbose_name='Тип')),
                ('cost', models.FloatField(blank=True, default=0, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Позиция инвентаря',
                'verbose_name_plural': 'Позиции инвентаря',
            },
        ),
        migrations.CreateModel(
            name='ItemCountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='г', max_length=10, verbose_name='Способ исчисления')),
            ],
            options={
                'verbose_name': 'Тип исчисления',
                'verbose_name_plural': 'Типы исчисления',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Заведение', max_length=25, verbose_name='Название')),
                ('adres', models.CharField(default='Ул. __, д. __', max_length=50, verbose_name='Адрес')),
                ('preview', models.ImageField(blank=True, upload_to='images/placePreview', verbose_name='Превью')),
                ('percentForPlace', models.FloatField(blank=True, default=0, verbose_name='Процент заведению')),
                ('percentForWorker', models.FloatField(blank=True, default=0, verbose_name='Процент работнику')),
                ('govTitle', models.CharField(default='Юр. Имя', max_length=50, verbose_name='Юр. Имя')),
                ('unp', models.CharField(default='123456789', max_length=10, verbose_name='УНП')),
                ('govAdress', models.CharField(default=' ', max_length=50, verbose_name='Юр./почтовый адрес')),
                ('bankcode', models.CharField(blank=True, default=' ', max_length=10, verbose_name='Код банка')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Simple', max_length=20, verbose_name='Название позиции')),
                ('cost', models.FloatField(default=23.0, verbose_name='Стоимость позиции')),
            ],
            options={
                'verbose_name': 'Позиция на продажу',
                'verbose_name_plural': 'Позиции на продажу',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Имя', max_length=20, verbose_name='Имя')),
                ('famName', models.CharField(default='Фамилия', max_length=20, verbose_name='Фамилия')),
                ('fathName', models.CharField(default='Отчество', max_length=20, verbose_name='Отчество')),
                ('vk', models.URLField(blank=True, default='vk.com/', verbose_name='ВК')),
                ('telegramNick', models.CharField(blank=True, default='NickName', max_length=20, verbose_name='Телеграмм')),
                ('date', models.DateField(default=datetime.datetime(2021, 4, 9, 7, 53, 18, 448422, tzinfo=utc), verbose_name='Дата приёма на работу')),
                ('avatar', models.ImageField(blank=True, upload_to='images/userAvatar', verbose_name='Аватар')),
                ('trainee', models.BooleanField(blank=True, default=True, verbose_name='Метка стажёра')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='Активный аккаунт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 7, 53, 18, 456422, tzinfo=utc), verbose_name='Время открытия смены')),
                ('endTime', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 7, 53, 18, 456422, tzinfo=utc), verbose_name='Время закрытия смены')),
                ('isOpen', models.BooleanField(default=True, verbose_name='Открыта ли смена')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий к окончанию смены')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.place', verbose_name='Заведение')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.profile', verbose_name='Сортудник')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'get_latest_by': 'endTime',
            },
        ),
        migrations.CreateModel(
            name='StartSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Количесвто')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.item', verbose_name='Позиция')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Начало смены',
                'verbose_name_plural': 'Начала смен',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default=' ', verbose_name='Комментарий')),
                ('positionType', models.CharField(blank=True, choices=[('FG', 'Гостю'), ('FS', 'Себе'), ('B', 'Бонусный')], default='FG', max_length=2, verbose_name='Тип кальяна')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.position', verbose_name='Позиция')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='+375331234567', max_length=13, verbose_name='Номер')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.profile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник и телефон',
                'verbose_name_plural': 'Сотрудники и телефоны',
            },
        ),
        migrations.CreateModel(
            name='ItemPositionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=20, verbose_name='Норма расхода')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.item', verbose_name='Материал')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.position', verbose_name='Позиция')),
            ],
        ),
        migrations.CreateModel(
            name='ItemItemRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphaItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alpha', to='data.item', verbose_name='Пополняемый расходник')),
                ('omegaItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omega', to='data.item', verbose_name='Пополняющий расходник')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='countType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.itemcounttype', verbose_name='Тип исчисления'),
        ),
        migrations.CreateModel(
            name='IBAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='IBAN BYN', max_length=15, verbose_name='Условное имя счёта')),
                ('iban', models.CharField(blank=True, default='', max_length=40, verbose_name='IBAN')),
                ('place', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data.place', verbose_name='Заведение')),
            ],
        ),
        migrations.CreateModel(
            name='EndSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Количесвто')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.item', verbose_name='Позиция')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Окончание смены',
                'verbose_name_plural': 'Окончания смен',
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/forSession', verbose_name='Сопроводительное изображение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('session', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Изображение для чека',
                'verbose_name_plural': 'Изображения для чеков',
            },
        ),
        migrations.CreateModel(
            name='DeleteOnSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Количесвто')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.item', verbose_name='Позиция')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Увоз',
                'verbose_name_plural': 'Увозы',
            },
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/forSession', verbose_name='Сопроводительное изображение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('session', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Изображение для ущерба',
                'verbose_name_plural': 'Изображения для ущерба',
            },
        ),
        migrations.CreateModel(
            name='AddToSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Количесвто')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.item', verbose_name='Позиция')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Привоз',
                'verbose_name_plural': 'Пирвозы',
            },
        ),
        migrations.CreateModel(
            name='AddedCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/forSession', verbose_name='Сопроводительное изображение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('cost', models.FloatField(default=0, verbose_name='Дополнительные расходы')),
                ('session', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Изображение для дополнительного расхода',
                'verbose_name_plural': 'Изображения для дополнительных расходов',
            },
        ),
    ]
