# Generated by Django 3.1.6 on 2021-03-19 18:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210316_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recvisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.FloatField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemType',
            field=models.CharField(blank=True, choices=[('v', 'Расходный материал'), ('c', 'Инвентарь')], default='c', max_length=1, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='place',
            name='recvisites',
            field=models.CharField(blank=True, max_length=16, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='position',
            name='positionType',
            field=models.CharField(blank=True, choices=[('FG', 'Гостю'), ('FS', 'Себе'), ('B', 'Бонусный')], default='FG', max_length=2, verbose_name='Тип кальяна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 18, 30, 1, 153772, tzinfo=utc), verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='session',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 18, 30, 1, 155789, tzinfo=utc), verbose_name='Время закрытия смены'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 18, 30, 1, 155789, tzinfo=utc), verbose_name='Время открытия смены'),
        ),
        migrations.CreateModel(
            name='ItemPositionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=20, verbose_name='Норма расхода')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.item', verbose_name='Материал')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.position', verbose_name='Позиция')),
            ],
        ),
        migrations.CreateModel(
            name='ItemItemRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphaItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alpha', to='data.item', verbose_name='Пополняемый расходник')),
                ('omegaItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omega', to='data.item', verbose_name='Пополняющий расходник')),
            ],
        ),
    ]
