# Generated by Django 3.1.6 on 2021-03-29 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210319_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='recvisites',
        ),
        migrations.AddField(
            model_name='profile',
            name='activate',
            field=models.BooleanField(blank=True, default=False, verbose_name='Активный аккаунт'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trainee',
            field=models.BooleanField(blank=True, default=True, verbose_name='Метка стажёра'),
        ),
        migrations.AddField(
            model_name='recvisites',
            name='adress',
            field=models.CharField(default=' ', max_length=50, verbose_name='Юр./почтовый адрес'),
        ),
        migrations.AddField(
            model_name='recvisites',
            name='bankcode',
            field=models.CharField(blank=True, default=' ', max_length=10, verbose_name='Код банка'),
        ),
        migrations.AddField(
            model_name='recvisites',
            name='ibanbyn',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='IBAN BYN'),
        ),
        migrations.AddField(
            model_name='recvisites',
            name='ibanusd',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='IBAN USD'),
        ),
        migrations.AddField(
            model_name='recvisites',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data.place', verbose_name='Заведение'),
        ),
        migrations.AddField(
            model_name='recvisites',
            name='title',
            field=models.CharField(default='Юр. Имя', max_length=50, verbose_name='Юр. Имя'),
        ),
        migrations.AddField(
            model_name='recvisites',
            name='unp',
            field=models.CharField(default='123456789', max_length=10, verbose_name='УНП'),
        ),
        migrations.AddField(
            model_name='session',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий к окончанию смены'),
        ),
        migrations.AlterField(
            model_name='place',
            name='preview',
            field=models.ImageField(blank=True, upload_to='images/placePreview', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/userAvatar', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 13, 39, 28, 554771, tzinfo=utc), verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='session',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 13, 39, 28, 555765, tzinfo=utc), verbose_name='Время закрытия смены'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 13, 39, 28, 555765, tzinfo=utc), verbose_name='Время открытия смены'),
        ),
        migrations.CreateModel(
            name='ImgForSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/forSession', verbose_name='Сопроводительное изображение')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Изображение для смены',
                'verbose_name_plural': 'Изображения для смен',
            },
        ),
    ]
