# Generated by Django 3.1.6 on 2021-03-30 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210330_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/forSession', verbose_name='Сопроводительное изображение')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Изображение для дополнительного расхода',
                'verbose_name_plural': 'Изображения для дополнительных расходов',
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/forSession', verbose_name='Сопроводительное изображение')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Изображение для чека',
                'verbose_name_plural': 'Изображения для чеков',
            },
        ),
        migrations.AlterModelOptions(
            name='damage',
            options={'verbose_name': 'Изображение для ущерба', 'verbose_name_plural': 'Изображения для ущерба'},
        ),
        migrations.AddField(
            model_name='damage',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='image',
            field=models.ImageField(upload_to='images/forSession', verbose_name='Сопроводительное изображение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 17, 21, 29, 633775, tzinfo=utc), verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='session',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 17, 21, 29, 634772, tzinfo=utc), verbose_name='Время закрытия смены'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 17, 21, 29, 634772, tzinfo=utc), verbose_name='Время открытия смены'),
        ),
        migrations.DeleteModel(
            name='ImgForSession',
        ),
        migrations.AddField(
            model_name='draft',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='addedcost',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена'),
        ),
    ]
