# Generated by Django 3.1.6 on 2021-03-30 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20210330_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedcost',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Дополнительные расходы'),
        ),
        migrations.AlterField(
            model_name='addedcost',
            name='session',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='session',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='session',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 17, 31, 59, 31509, tzinfo=utc), verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='session',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 17, 31, 59, 33504, tzinfo=utc), verbose_name='Время закрытия смены'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 17, 31, 59, 33504, tzinfo=utc), verbose_name='Время открытия смены'),
        ),
    ]
