# Generated by Django 3.1.6 on 2021-03-31 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20210330_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='percentForPlace',
            field=models.FloatField(blank=True, default=0, verbose_name='Процент заведению'),
        ),
        migrations.AddField(
            model_name='place',
            name='percentForWorker',
            field=models.FloatField(blank=True, default=0, verbose_name='Процент работнику'),
        ),
        migrations.AlterField(
            model_name='addedcost',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 10, 13, 40, 465115, tzinfo=utc), verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='session',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 10, 13, 40, 467110, tzinfo=utc), verbose_name='Время закрытия смены'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 10, 13, 40, 467110, tzinfo=utc), verbose_name='Время открытия смены'),
        ),
    ]
