# Generated by Django 3.1.6 on 2021-04-01 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20210401_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='IBAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='IBAN BYN', max_length=15, verbose_name='Условное имя счёта')),
                ('iban', models.CharField(blank=True, default='', max_length=40, verbose_name='IBAN')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='adress',
            field=models.CharField(default=' ', max_length=50, verbose_name='Юр./почтовый адрес'),
        ),
        migrations.AddField(
            model_name='place',
            name='bankcode',
            field=models.CharField(blank=True, default=' ', max_length=10, verbose_name='Код банка'),
        ),
        migrations.AddField(
            model_name='place',
            name='govTitle',
            field=models.CharField(default='Юр. Имя', max_length=50, verbose_name='Юр. Имя'),
        ),
        migrations.AddField(
            model_name='place',
            name='unp',
            field=models.CharField(default='123456789', max_length=10, verbose_name='УНП'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 12, 13, 25, 443328, tzinfo=utc), verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='session',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 12, 13, 25, 445287, tzinfo=utc), verbose_name='Время закрытия смены'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 12, 13, 25, 445287, tzinfo=utc), verbose_name='Время открытия смены'),
        ),
        migrations.DeleteModel(
            name='Recvisites',
        ),
        migrations.AddField(
            model_name='iban',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data.place', verbose_name='Заведение'),
        ),
    ]
