# Generated by Django 3.1.6 on 2021-04-01 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20210401_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='adress',
            new_name='govAdress',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 16, 12, 14, 981807, tzinfo=utc), verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='session',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 16, 12, 14, 983759, tzinfo=utc), verbose_name='Время закрытия смены'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 16, 12, 14, 983759, tzinfo=utc), verbose_name='Время открытия смены'),
        ),
    ]
